theme: minima
title: Naroa Garayalde al habla
author: Naroa Garayalde
description: En este apartado encontrarás mi lado más personal, junto a mis aficiones y mis trabajos realizados. Espero que sea de tu agrado <3
